# -*- coding: utf-8 -*-
"""SentMarket.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blXhr1amFb9D0T52HdWVicnD2a9WzJkw

# **Processamento de Linguagem Natural [2025-Q3]**
Prof. Alexandre Donizeti Alves

### **PROJETO PRÁTICO** [LangChain + Grandes Modelos de Linguagem]

O **PROJETO PRÁTICO** deve ser feito utilizando o **Google Colab** com uma conta sua vinculada ao Gmail. O link do seu notebook armazenado no Google Drive e o link de um repositório no GitHub devem ser enviados usando o seguinte formulário:

> https://forms.gle/D4gLqP1iGgyn2hbH8


**IMPORTANTE**: A submissão deve ser feita até o dia **07/12 (domingo)** APENAS POR UM INTEGRANTE DA EQUIPE, até às 23h59. Por favor, lembre-se de dar permissão de ACESSO IRRESTRITO para o professor da disciplina.

### **EQUIPE**

---

**POR FAVOR, PREENCHER OS INTEGRANDES DA SUA EQUIPE:**


**Integrante 01:**

`Caio Pereira Neris RA: 11202230288`

**Integrante 02:**

`Matheus Batistelli Vignola RA: 11202230362`

### **GRANDE MODELO DE LINGUAGEM (*Large Language Model - LLM*)**

---

Cada equipe deve selecionar um Grande Modelo de Linguagem (*Large Language Model - LMM*).

Por favor, informe os dados do LLM selecionada:

>


**LLM**:

> ChatGPT (OpenAI)

**Link para a documentação oficial**:
https://platform.openai.com/docs/api-reference/introduction

### **API (Opcional)**
---

Por favor, informe os dados da API selecionada:

**API**: NewsApi

**Site oficial**: https://newsapi.org/

**Link para a documentação oficial**: https://newsapi.org/docs

### **DESCRIÇÃO**
---

Implementar um `notebook` no `Google Colab` que faça uso do framework **`LangChain`** (obrigatório) e de um **LLM** aplicando, no mínimo, DUAS técnicas de PLN. As técnicas podem ser aplicada em qualquer córpus obtido a partir de uma **API** ou a partir de uma página Web.

O **LLM** e a **API** selecionados devem ser informados na seguinte planilha:

> https://docs.google.com/spreadsheets/d/1iIUZcwnywO7RuF6VEJ8Rx9NDT1cwteyvsnkhYr0NWtU/edit?usp=sharing

>
As seguintes técnicas de PLN podem ser usadas:

*   Correção Gramatical
*   Classificação de Textos
*   Análise de Sentimentos
*   Detecção de Emoções
*   Extração de Palavras-chave
*   Tradução de Textos
*   Sumarização de Textos
*   Similaridade de Textos
*   Reconhecimento de Entidades Nomeadas
*   Sistemas de Perguntas e Respostas
>

**IMPORTANTE:** É obrigatório usar o e-mail da UFABC.

### **CRITÉRIOS DE AVALIAÇÃO**
---

Serão considerados como critérios de avaliação os seguintes pontos:

* Uso do framework **`LangChain`**.

* Escolha e uso de um **LLM**.

* Escolha e uso de uma **API** ou **Página Web**.

* Projeto disponível no Github.

* Apresentação (5 a 10 minutos).

* Criatividade no uso do framework **`LangChain`** em conjunto com o **LLM** e a **API**.

**IMPORTANTE**: todo o código do notebook deve ser executado. Código sem execução não será considerado.

### **IMPLEMENTAÇÃO: SentMarket**
---

# Neste trabalho, implementamos uma ferramenta de análisa do mercado financeiro por meio de notícias (usando a NewsAPI), possibilitando:



1.   Análise de sentimentos:

*   da economia brasileira,
*   sua comparação com a economia de outros países,
*   de empresas, setores e ações específicas  

2.   Classificação de relevância e similaridade das notícias para cenário econômico, extraindo palavras-chaves

3. Sumarização do cenário econômico

4. Sistema de perguntas e respostas sobre a economia
"""



import os
import requests
import pandas as pd
from datetime import date, timedelta

from openai import OpenAI
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document
#from langchain_classic.chains import create_retrieval_chain
#from langchain_classic.chains.combine_documents import create_stuff_documents_chain

#import streamlit as st

github_token = "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" # st.secrets["GITHUB_TOKEN"]
news_api = "66d358d7fc7242d7a1b01c6a3a0e6d1e" #st.secrets["NEWS_API"]


# URL base da NewsAPI
url = "https://newsapi.org/v2/everything"

# Mapeamento país → idioma principal
IDIOMA_POR_PAIS = {
    "brasil": "pt",
    "portugal": "pt",
    "angola": "pt",
    "moçambique": "pt",
    "estados unidos": "en",
    "reino unido": "en",
    "argentina": "es",
    "espanha": "es",
    "méxico": "es",
    "frança": "fr",
    "alemanha": "de",
    "itália": "it",
    "japão": "ja",
    "china": "zh",
    "rússia": "ru",
    "índia": "hi",
}

def idioma_do_pais(pais: str):
    pais_lower = pais.lower().strip()
    return IDIOMA_POR_PAIS.get(pais_lower, "en")  # padrão: inglês

def pesquisar_noticias(pais):
    termos = [
        f"economia {pais}", f"economia do {pais}",
        "Banco Central", "Central Bank",
        "Selic", "interest rate", "inflation", "PIB", "GDP",
        "Ibovespa", "B3", "financial market", "unemployment"
    ]

    query = " OR ".join([f'"{t}"' for t in termos])

    idioma = idioma_do_pais(pais)

    params = {
        "q": query,
        "language": idioma,
        "sortBy": "relevancy",  # ou "publishedAt" se quiser as mais recentes
        "pageSize": 30, #max é 100, mas o GPT 4 dá erro de excesso de tokens
        "apiKey": news_api,
        "from": (date.today() - timedelta(days=7)).isoformat(),
        "to": date.today().isoformat(),
    }
    response = requests.get("https://newsapi.org/v2/everything", params=params)
    data = response.json()

    if data.get("status") != "ok":
        print(f"❌ Erro ao buscar notícias: {data.get('message')}")
        return pd.DataFrame()

    noticias = data.get("articles", [])
    articles = pd.DataFrame(noticias)

    if articles.empty:
        print("⚠️ Nenhuma notícia encontrada.")
        return articles

    # Corrige coluna source
    if "source" in articles.columns:
        articles["source"] = articles["source"].apply(lambda s: s.get("name") if isinstance(s, dict) else s)

    # Mantém apenas colunas principais
    colunas = ["source", "title", "description", "url", "publishedAt"]
    for col in colunas:
        if col not in articles.columns:
            articles[col] = None

    articles = articles[colunas]

    print(f"Total de notícias encontradas: {len(articles)}")
    return articles

noticias_brasil = pesquisar_noticias("Brasil")


print("Total de resultados:", len(noticias_brasil))

"""https://github.com/marketplace/models/azure-openai/o4-mini"""

from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
import json
import re




# Modelo apontando para o endpoint do GitHub Models
modelo = ChatOpenAI(
    model="openai/gpt-4o",
    temperature=0.1,
    api_key= github_token,
    base_url="https://models.github.ai/inference"
)
def analise_pais(pais, noticias: pd.DataFrame):
    # Converte o DataFrame em string JSON (modelo entende melhor)
    noticias_json = noticias.to_json(orient="records", force_ascii=False)

    # Template do prompt
    prompt = PromptTemplate(
        input_variables=["pais", "dataframe"],
        template=(
            """Você irá receber um dataframe (em formato JSON) com notícias sobre a economia do país {pais}.
    Seu objetivo é devolver um novo dataframe JSON com as colunas:
    - 'source', 'title', 'description', 'url', 'publishedAt'
    - e as novas colunas: 'palavra chave', 'classificação', 'similaridade'

    Etapas:
    1. Leia o título ('title') de cada notícia e classifique todas as n notícias de 1 (mais relevante) a n (menos relevante),
    segundo o critério: "Quais explicam melhor o cenário econômico atual e futuro do país?".
    2. Para cada título, identifique a 'palavra chave' (termo mais importante que descreve o tema).
    3. Calcule 'similaridade' = número de outras notícias que tratam do mesmo tema (mesma palavra chave).
    4. Retorne apenas as 10 notícias mais relevantes (classificação de 1 a 10).
    5. Após o dataframe, escreva um breve resumo do cenário econômico atual do país.

    ⚠️ IMPORTANTE: retorne SOMENTE um JSON, com esta estrutura:

    {{
    "data": ...,
    "resumo": "..."
    }}

    Input:
    {{"data": {dataframe}}}

    Considere o país: {pais}
    """
        )
    )

    # Cria a cadeia
    chain = prompt | modelo

    # Executa
    resposta = chain.invoke({"pais": pais, "dataframe": noticias.to_string()})

    # Exibe e tenta converter a parte JSON da resposta em DataFrame
    conteudo = resposta.content.strip()

    # 🔧 Limpeza para remover blocos ```json ... ```
    conteudo_limpo = re.sub(r"^```json\s*|\s*```$", "", conteudo, flags=re.DOTALL).strip()

    try:
        result = json.loads(conteudo_limpo)
        df_resultado = pd.DataFrame(result["data"])
        resumo = result.get("resumo", "")

        # Exibe resumo com melhor formatação
        print(f"\n📰 **Resumo do cenário econômico ({pais}):**\n")
        print(resumo.strip())

        return df_resultado, resumo

    except Exception as e:
        print("❌ Não foi possível converter a resposta em DataFrame.")
        print("Erro:", e)
        print("\nConteúdo limpo recebido:\n", conteudo_limpo[:500], "...")
        return None, None

# Teste
paises = ["Brasil", "Estados Unidos", "Argentina"]

# for pais in paises:
#     analise_pais(pais, pesquisar_noticias(pais))

def pesquisar_acoes(acao):
    """
    Busca notícias recentes sobre uma ação (empresa ou ticker) usando a NewsAPI.
    O nome pode ser o ticker (ex: 'PETR4') ou o nome da empresa (ex: 'Petrobras').
    Retorna um DataFrame com as notícias relevantes.
    """

    # Normaliza o nome e gera termos de busca
    termos = [
        f'"{acao}"',                                  # nome direto ou ticker
        f'"ações {acao}"',                            # ações + nome
        f'"papéis da {acao}"',                        # expressão usada na mídia
        f'"{acao} na B3"',                            # referência à bolsa brasileira
        f'"{acao} stocks"',                           # versão em inglês
        f'"{acao} shares"',                           # ações em inglês
        f'"{acao} empresa"',                          # empresa
        f'"{acao} earnings"',                         # resultados trimestrais
        f'"{acao} lucro"',                            # lucro
        f'"{acao} dividendos"',                       # dividendos
        f'"{acao} preço da ação"',                    # preço
        f'"{acao} cotação"',                          # cotação
        f'"{acao} mercado"',                           # mercado
        f'"{acao} Brasil"',                           # nome + país
        f'"{acao} notícias"',
        f'"{acao} investimento"',
        ]

    # Combina termos com OR
    query = " OR ".join(termos)

    # Escolhe idioma dinamicamente (se ação for de empresa brasileira)
    idioma = "pt" if any(x in acao.lower() for x in ["b3", "brasil", "petr", "vale", "itau", "bradesco"]) else "en"

    params = {
        "q": query,
        "language": idioma,
        "sortBy": "publishedAt",
        "pageSize": 50,
        "apiKey": news_api,
        "from": (date.today() - timedelta(days=7)).isoformat(),
        "to": date.today().isoformat(),
    }

    # Requisição à API
    response = requests.get("https://newsapi.org/v2/everything", params=params)
    data = response.json()

    # Extrai artigos
    articles = data.get("articles", [])
    if not articles:
        print(f"Nenhuma notícia encontrada para {acao}.")
        return pd.DataFrame()

    # Converte em DataFrame
    df = pd.DataFrame(articles)[["source", "title", "description", "url", "publishedAt"]]
    print(f"🔎 {len(df)} notícias encontradas para {acao}.")
    return df

# df_petr = pesquisar_acoes("Petrobras")
# df_apple = pesquisar_acoes("Apple")
# df_itau = pesquisar_acoes("Itaú Unibanco")

def analise_acao(acao, noticias: pd.DataFrame):
    # Converte o DataFrame em string JSON (modelo entende melhor)
    noticias_json = noticias.to_json(orient="records", force_ascii=False)

    # Template do prompt
    prompt = PromptTemplate(
        input_variables=["acao", "dataframe"],
        template=(
            """Você irá receber um dataframe (em formato JSON) com notícias sobre a ação {acao}.
Seu objetivo é devolver **apenas um texto** com uma análise de sentimento sobre essa ação, com base nas notícias.

No início da resposta, coloque:
- Um número de 1 a 10 indicando o sentimento geral do mercado.
- Entre parênteses, o tipo de sentimento:
  * 1–4: Pessimismo
  * 5–7: Neutro
  * 8–10: Otimismo

Depois disso, escreva um pequeno resumo explicando o motivo dessa avaliação.

Input:
{{"noticias": {dataframe}}}

Considere a ação: {acao}
"""
        )
    )

    # Cria a cadeia
    chain = prompt | modelo

    # Executa a cadeia e retorna o texto diretamente
    resposta = chain.invoke({"acao": acao, "dataframe": noticias_json})

    print(f"\n🧠 Análise de sentimento para {acao}:\n")
    #print(resposta.content.strip())
    print("\n")

    return resposta


acoes = ['VALE3', 'Petrobras', 'Banco Itaú SA', 'Apple'] #, 'BRFS3.SA', 'ABEV3.SA', 'WEGE3.SA',
           # 'EGIE3.SA', 'LREN3.SA', 'BBAS3.SA', 'SLCE3.SA' ]

# for acao in acoes:
#     analise_acao(acao, pesquisar_acoes(acao))

import langchain
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document
from langchain_core.runnables import RunnableLambda

def pesquisar_noticias_por_termo(termos):

    query = " OR ".join([f'"{t}"' for t in termos])

    #idioma = idioma_do_pais(pais)

    params = {
        "q": query,
        "language": "pt", #idioma,
        "sortBy": "relevancy",  # ou "publishedAt" se quiser as mais recentes
        "pageSize": 30, #max é 100, mas o GPT 4 dá erro de excesso de tokens
        "apiKey": news_api,
        "from": (date.today() - timedelta(days=7)).isoformat(),
        "to": date.today().isoformat(),
    }
    response = requests.get("https://newsapi.org/v2/everything", params=params)
    data = response.json()

    if data.get("status") != "ok":
        print(f"❌ Erro ao buscar notícias: {data.get('message')}")
        return pd.DataFrame()

    noticias = data.get("articles", [])
    articles = pd.DataFrame(noticias)

    if articles.empty:
        print("⚠️ Nenhuma notícia encontrada.")
        return articles

    # Corrige coluna source
    if "source" in articles.columns:
        articles["source"] = articles["source"].apply(lambda s: s.get("name") if isinstance(s, dict) else s)

    # Mantém apenas colunas principais
    colunas = ["source", "title", "description", "url", "publishedAt"]
    for col in colunas:
        if col not in articles.columns:
            articles[col] = None

    articles = articles[colunas]

    print(f"Total de notícias encontradas: {len(articles)}")
    return articles

#================================================================================================================================

def df_to_documents(df):
    docs = []
    for _, row in df.iterrows():
        # Adicionei tratamento para caso description seja None
        desc = row.get('description', '')
        if desc is None: desc = ""

        texto = (
            f"Título: {row['title']}\n"
            f"Descrição: {desc}\n"
            f"Fonte: {row['source']}\n"
            f"Data: {row['publishedAt']}\n"
        )
        docs.append(Document(page_content=texto))
    return docs

# --- PROMPT 1: APENAS PARA O ANALISTA (RAG) ---
# Sem instruções de busca aqui, foco apenas na análise.
prompt_analista_sistema = (
    """Você é um analista econômico sênior.
    Sua tarefa é responder à pergunta do usuário utilizando as notícias fornecidas como base principal (Contexto).

    Diretrizes:
    1. **Prioridade:** Use os fatos apresentados nas notícias (Contexto) para fundamentar sua resposta. Cite as fontes quando possível.
    2. **Conhecimento Híbrido:** Se as notícias fornecidas forem insuficientes, vagas ou muito antigas, VOCÊ DEVE complementar a resposta com seu próprio conhecimento sobre economia e finanças.
    3. **Transparência:** Se usar seu conhecimento próprio, deixe claro (ex: "Embora as notícias não mencionem, historicamente...").
    4. **Formato:** Seja direto, profissional e estruturado.

    Se as notícias forem totalmente irrelevantes para o tema, ignore-as e responda com seu conhecimento, avisando o usuário que as notícias recentes não ajudaram.
    """
)

prompt_rag = ChatPromptTemplate.from_messages(
    [
        ("system", prompt_analista_sistema),
        ("system", "CONTEXTO (Notícias Recentes):\n\n{context}"),
        ("human", "{input}"),
    ]
)

#================================================================================================================================

def chatbot_news(pergunta):
    #pergunta = input("Digite sua pergunta: ")

    # Aqui usamos um prompt "inline" simples, pois é uma tarefa rápida
    prompt_busca = f"""
    Aja como um extrator de palavras-chave para uma API de notícias.
    Analise a pergunta: "{pergunta}"

    Retorne APENAS os termos principais para busca (ex: "Inflação Brasil", "Apple stock", "Taxa Selic").
    Se for sobre um país, coloque o nome do país, mas sempre junto do tema. Cada termo deve ser um tópico completo (ex: "desemprego brasil"). Não retorne palavras isoladas como "Brasil", "economia", etc. Não use frases longas.
    Saída SEMPRE no formato: termo1, termo2, termo3

    Não use pontuação, não use aspas, apenas texto cru.
    """

    termo_busca = modelo.invoke(prompt_busca).content.strip()

    print(f"\n🔎 Termo interpretado: {termo_busca}")
    print(f"📡 Buscando notícias...")

    #Buscar notícias
    try:
        noticias_df = pesquisar_noticias_por_termo(termo_busca)
    except Exception as e:
        print(f"Erro na busca: {e}")
        return

    # Se não achar notícias, o modelo ainda pode tentar responder
    docs = []
    if not noticias_df.empty:
        docs = df_to_documents(noticias_df)
        print(f"✅ {len(docs)} notícias encontradas e enviadas ao modelo.")
    else:
        print("⚠️ Nenhuma notícia encontrada. O modelo responderá apenas com conhecimento prévio.")

    # O truque do RunnableLambda para injetar os docs que já temos
    retriever = RunnableLambda(lambda x: docs)

    qa_chain = create_stuff_documents_chain(modelo, prompt_rag)
    rag_chain = create_retrieval_chain(retriever, qa_chain)

    #Gerar Resposta Final
    print("\n🧠 Gerando análise...")
    resultado = rag_chain.invoke({"input": pergunta})

    print("\n" + "="*40)
    print(resultado["answer"])
    print("="*40 + "\n")
    return resultado["answer"]